# Generated by Django 4.0.8 on 2024-06-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0003_remove_comment_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='coment',
            new_name='car',
        ),
    ]
