# Generated by Django 4.0.8 on 2024-06-14 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0006_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_ordered',
            new_name='date',
        ),
    ]
